# Generated by Django 3.2.8 on 2021-10-10 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='loanfund',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanterm',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanfund',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='loanfund',
            name='provider',
        ),
        migrations.AddField(
            model_name='loanfund',
            name='provider',
            field=models.ManyToManyField(related_name='provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='loanterm',
            name='customer',
        ),
        migrations.AddField(
            model_name='loanterm',
            name='customer',
            field=models.ManyToManyField(related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanfund',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.status'),
        ),
        migrations.AlterField(
            model_name='loanterm',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.status'),
        ),
    ]
