# Generated by Django 3.2.8 on 2021-10-10 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20211010_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanfund',
            name='provider',
        ),
        migrations.AddField(
            model_name='loanfund',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='loanterm',
            name='customer',
        ),
        migrations.AddField(
            model_name='loanterm',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
