# Generated by Django 3.2.8 on 2021-10-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0004_auto_20211011_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanfund',
            name='allowed',
            field=models.ManyToManyField(default=1, to='auth.Group'),
        ),
    ]
