# Generated by Django 3.2.8 on 2021-10-11 19:21

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0005_loanfund_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanfund',
            name='allowed',
            field=models.ManyToManyField(default=base.models.LoanFund.allowedDefault, to='auth.Group'),
        ),
    ]
