# Generated by Django 3.2.8 on 2021-10-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='funds',
            field=models.ManyToManyField(to='base.LoanFund'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='loans',
            field=models.ManyToManyField(to='base.LoanTerm'),
        ),
    ]
