# Generated by Django 3.2.8 on 2021-10-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20211011_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanterm',
            name='status',
        ),
        migrations.AlterField(
            model_name='loanfund',
            name='status',
            field=models.CharField(choices=[('NA', 'No Applicants'), ('IP', 'In Process'), ('AP', 'Approved'), ('DN', 'Denied')], default='NA', max_length=2),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
