# Generated by Django 3.2.8 on 2021-10-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0010_auto_20211012_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanterm',
            name='allowed',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='loanterm',
            name='status',
            field=models.CharField(choices=[('NA', 'No Applicants'), ('IP', 'In Process'), ('AP', 'Approved'), ('DN', 'Denied')], default='NA', max_length=2),
        ),
    ]
