# Generated by Django 3.2.8 on 2021-10-13 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_auto_20211012_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanfund',
            old_name='fund_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='loanterm',
            old_name='loan_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='loanfund',
            name='allowed',
        ),
        migrations.RemoveField(
            model_name='loanfund',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loanfund',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='loanfund',
            name='status',
        ),
        migrations.RemoveField(
            model_name='loanterm',
            name='allowed',
        ),
        migrations.RemoveField(
            model_name='loanterm',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loanterm',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='loanterm',
            name='status',
        ),
        migrations.CreateModel(
            name='termApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IP', 'In Process'), ('AP', 'Approved'), ('DN', 'Denied')], default='IP', max_length=2)),
                ('amount', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('term_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.loanterm')),
            ],
        ),
        migrations.CreateModel(
            name='fundApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IP', 'In Process'), ('AP', 'Approved'), ('DN', 'Denied')], default='IP', max_length=2)),
                ('amount', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fund_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.loanfund')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
