# Generated by Django 3.2.8 on 2021-10-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20211013_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanfund',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanterm',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
